### ISSUE TITLE
test for proper (or stale) grabix index?

### ISSUE THREAD

**Issue by arq5x** [arq5x/gemini#392]
https://groups.google.com/forum/#!topic/gemini-variation/7tMwpZMMZfw

**Comment by oleraj** [comment]
Unfortunately, what I think needs to be done -- or what worked for me -- is if the timestamp of the .vcf.gz file is later than the timestamp of the grabix index, both the .vcf.gz and grabix index need to be recreated from the original vcf file (assuming the .vcf.gz file was created by gemini and not the user).  In my test with just remaking the grabix index, I still got an error.  Maybe in some cases simply remaking the index file would help (and it's probably a good idea anyway, since in theory the index should always have a later timestamp than the vcf.gz file).  But it may not get rid of the error.  This timestamp checking could probably be done at the step where it checks for the .vcf.gz file before making it, adding one more condition to be satisfied before skipping the creation of the .vcf.gz file.

**Comment by arq5x** [comment]
Resolved in master.
