### ISSUE TITLE
Tab character not printed for empty HOM_ALT_samples column with --show-samples

### ISSUE THREAD

**Issue by VelNZ** [arq5x/gemini#535]
I recently added the --show-samples parameter to my queries and found that when the last "HOM_ALT_samples" column is empty, an extra tab character is not printed for it. I have a specific use case where I need all rows to have the same number of columns and this is causing issues with this. It might be worth checking whether the same behaviour is present for the "HET_samples" column.

**Comment by arq5x** [comment]
Are you sure that tabs aren't actually being printed but something downstream is clobbering consecutive whitespace?  I ask because it looks to work as expected with 0.16.3. For example, the first record below lacks het_samples and there are two consecutive tabs. The 2nd through fourth lines have two consecutive tabs at the end because hom_alt_samples is lacking.  If you use a global trimming function that strips _all_ whitespace, that tab at the end might be being chopped off. For example, Pyhton's `strip()` clears all whitespace by default, but if we used `strip('\n') it would preserve the tab.

All this said, perhaps it is worth inserting a visiable "empty" character such as "." to prevent this.

    gemini query -q "select chrom, start, end from variants where impact_severity != 'LOW'" \
                          --show-samples \
                          --header trio.trim.vep.denovo.db \
    | cat -t \
    | head
    chrom^Istart^Iend^Ivariant_samples^Ihet_samples^Ihom_alt_samples
    chr2^I45894^I45895^I1805,1847^I^I1805,1847
    chr2^I242799^I242800^I1805,1847,4805^I1805,1847,4805^I
    chr2^I243503^I243504^I1805,1847,4805^I1805,1847,4805^I
    chr2^I243566^I243567^I1805,1847,4805^I1805,1847,4805^I
    chr2^I269351^I269352^I1805,1847,4805^I1805,1847,4805^I
    chr2^I676176^I676177^I1805,1847,4805^I^I1805,1847,4805
    chr2^I1168780^I1168781^I1847,4805^I1847,4805^I
    chr2^I1271229^I1271230^I4805,1847^I4805^I1847
    chr2^I1320142^I1320143^I1805,1847,4805^I1805^I1847,4805

**Comment by VelNZ** [comment]
Sorry I should have mentioned I'm running 0.15.1! If this is something that has been modified since then, please close the issue.

If not, I attach screenshots of an example, one has 3 columns (triangles are tab characters) for the --show-samples 3 columns and one has 2 where there is no value for HOM_ALT_samples. This is a raw output from Gemini with no post-processing (as far as I can see).

<img width="705" alt="screen shot 2015-08-20 at 12 35 13 pm" src="https://cloud.githubusercontent.com/assets/10110412/9374301/fc22522e-4737-11e5-88c9-c5d84f61cc16.png">
<img width="514" alt="screen shot 2015-08-20 at 12 34 27 pm" src="https://cloud.githubusercontent.com/assets/10110412/9374302/fc648068-4737-11e5-9dbf-09e9bed3de96.png">

**Comment by brentp** [comment]
@VelNZ could you give 0.16.3 a try and let us know. We can leave this open in case the problem has persisted.

**Comment by arq5x** [comment]
Closing, but please reopen if this is an issue in 0.17.0
