### ISSUE TITLE
add allele frequency confidence intervals to annotation files

### ISSUE THREAD

**Issue by brentp** [arq5x/gemini#609]
Since we preprocess the annotation files anyway, we could calculate the confidence intervals of the alllele frequencies for any annotation that also gives the number of chromosomes from which the AF was estimated. We'd update the header and the INFO field with the af lims.
This was originally discussed in #568 

A function to calculate the confidence intervals is here: https://gist.github.com/brentp/172e213a87f3f6188891

**Comment by oleraj** [comment]
Hi @brentp, has this been added as a column to the gemini db? I don't see it in a database created with gemini 0.20.0.  What is the column name(s)?  
Thanks

**Comment by brentp** [comment]
no, it has not been added, but I think the utility is marginal.

**Comment by oleraj** [comment]
Hmm, not sure what you mean.  I've been hesitant to use the max_aaf_all column as a filter for just the reasons that @jxchong mentioned (i.e., lack of precision of the empirical allele frequency in small subpopulations) and this seemed like a solution that I'm more comfortable with.  Has @jxchong changed her mind as well?

**Comment by oleraj** [comment]
Just a bit more information about the potential usefulness of this, in case it is helpful.  The folks at ClinGen are applying similar methods from my discussions with Matt Lebo and the folks at the UDP are using this type of strategy as well (though instead of the Jeffreys interval, using Wilson's score for determining confidence interval, which is I believe equation #3 in the paper that Jessica cited).  [Here](http://journals.plos.org/plosone/article?id=10.1371/journal.pone.0085925) is a paper discussing the value of using confidence intervals for allele frequency estimates (not sure if it is the best, but highlights the point at least).  I think other users would appreciate it as well once they understand the value.  I suppose I could still precompute the values and add them to the database as custom annotations but if gemini did this for us it would require less pre-processing and maintenance, keeping up with new versions of the databases as they are updated.
