### ISSUE TITLE
gene_summary table contains 'None' (not NULL) gene entries

### ISSUE THREAD

**Issue by muraveill** [arq5x/gemini#625]
With version 0.18.0:

sqlite> select gene from gene_summary where gene='None';
None
None
None

**Comment by brentp** [comment]
this must have been present in earlier version as well. I'll have a look at this for 0.18.1

**Comment by muraveill** [comment]
We rebuilt the databases after a brand new installation on a new machine, and still get Nones:

    sqlite> select count(*) from gene_summary where gene='None';
    26455
    sqlite> select count(*) from gene_summary;
    121502

Not blocking though, just untidy.

**Comment by jxchong** [comment]
Which version of VEP are you using and which options?

I've been testing VEP v82 and v83. I see gene=='None' for variants where the variant is annotated as: `impact=='regulatory_region_variant'` if I run VEP v83 with the `--regulatory` option. (gene==None because the variant is not in a gene)  http://uswest.ensembl.org/info/genome/variation/predicted_data.html#consequences

**Comment by muraveill** [comment]
It is VEP v82. Unfortunately I don't always have the vcf to check, but I was quite sure that the 'None' was coming from Python (VEP is written in Perl).

**Comment by brentp** [comment]
This has been present for a long time. I've just made a change to set those to NULL rather than the 'None' string.
