### ISSUE TITLE
integrate geno2mp

### ISSUE THREAD

**Issue by brentp** [arq5x/gemini#643]
via @jxchong 

geno2mp_hpo_ct as a single column and set it to NULL if it's not present.

the file is available here: http://geno2mp.gs.washington.edu/download/Geno2MP.variants.vcf

**Comment by jxchong** [comment]
Would it be more useful to make it -1? Then you don't have to do `geno2mp_hpo_ct <= 5 or geno2mp_hpo_ct is NULL`  On the other hand, is there a reason to NOT make it -1 and leave it NULL?

**Comment by brentp** [comment]
I was thinking that one would probably only ever want to differentiate between presence and absence. I can use -1 if you think that's more useful.

**Comment by jxchong** [comment]
Possibly -1 is more universally useful because you can always query absence by `geno2mp_hpo_ct == -1` (since every variant in Geno2MP has to have at least one HPO profile attached to it).

**Comment by jxchong** [comment]
FYI whenever you get around to adding this to GEMINI, I tried doing taking a variant-decomposed version of this file and annotating a database with it:
`gemini annotate -f Geno2MP.variants.VT.vcf.gz -e HPO_CT -t integer -o sum -c geno2mp_hpo_ct mydata.db`
GEMINI claimed it was successful `updated 19190 variants`
but `gemini query -q "select distinct(geno2mp_hpo_ct) from variants" mydata.db` yielded "None"

If instead of telling it to `sum`, I tell GEMINI to use `first` as in `gemini annotate -f Geno2MP.variants.120915.VT.vcf.gz -e HPO_CT -t integer -o first -c geno2mp_hpo_ct mydata.db` the data gets imported correctly. I've never tried `-o sum` before so I'm not sure if this is my mistake or a bug.

**Comment by brentp** [comment]
Hi @jxchong, I have just fixed this. It will be in 0.18.1 release and you can also get around it by using -t float instead of -t integer. Thanks for reporting, as usual.

I'm working right now on getting geno2mp into gemini load.
