### ISSUE TITLE
sqlalchemy.exc.StatementError: (exceptions.TypeError) float() argument must be a string or a number

### ISSUE THREAD

**Issue by komalsrathi** [arq5x/gemini#751]
Hi,

I am having trouble annotating my vcf with `CP` field from ESP6500SI.all.snps_indels.tidy.v2.vcf.gz. 

This is a small section of my config file `test.conf`:
```
[[annotation]]
file = "ExAC.r0.3.sites.vep.tidy.vcf.gz"
fields = ["AC_Adj", "AN_Adj"]
names = ["exac_ac_all", "exac_an_all"]
ops = ["self", "self"]

[[annotation]]
file = "ESP6500SI.all.snps_indels.tidy.v2.vcf.gz"
fields = ["FG","AAC", "PH", "CP"]
names = ["functionGVS", "aminoAcidChange", "polyPhen", "scorePhastCons"]
ops = ["self", "self", "self", "self"]
```

These are my commands:

```
vcfanno -p 4 -base-path $GEMINI_ANNO -lua test.lua test.conf $VCF | bgzip -c > anno.vcf.gz
gemini_python $VCF2DB/vcf2db.py --legacy-compression anno.vcf.gz sample.pedfile my.db
```

The error I am getting is in the attached log file:  
[gemini_log.txt](https://github.com/arq5x/gemini/files/330687/gemini_log.txt)

I know there is some issue with `CP i.e. scorePhastCons` because I have checked - the error disappears when I remove that particular field from test.conf.

**Comment by brentp** [comment]
So, the problem is that Number=1, so the loader tries to load it, but there are 2 variants at the problematic site in ESP with the exact same REF and ALT (one of them gets normalized to be the same as an existing variant with vt normalize). So, vcfanno reports 2 values at that site.

You can get around it for now by using op of "max" for "CP". I'll try to think of how to handle this better both in vcfanno and in vcf2db.

I'm adding the small test-case here to reproduce for my testing with:
```
vcfanno -lua <(echo) <(zcat t.conf.gz) t.vcf.gz  | grep scorePhastCons
```


[t.vcf.gz](https://github.com/arq5x/gemini/files/330730/t.vcf.gz)
[t.conf.gz](https://github.com/arq5x/gemini/files/330733/t.conf.gz)

**Comment by brentp** [comment]
.. so for now, just use "max", and let me know if you hit any other issues.

**Comment by komalsrathi** [comment]
Alright, I will try it and close the issue if that works. Thanks!!

**Comment by leipzig** [comment]
Are these both hg38?

**Comment by komalsrathi** [comment]
Yep.
