### ISSUE TITLE
question regarding sqlite Blob

### ISSUE THREAD

**Issue by dridk** [arq5x/gemini#948]
Hi, 

I see you store sample data ( like genotype ) as blob into sqlite database. 
I am really curious how do you query this fields in raw sql ? 
for instance, how to get variant where sample boby is heterozygous ?

**Comment by brentp** [comment]
Hi, we have to decode the blob to do any queries on genotypes so it's not very efficient. If you use vcf2db.py  there is an option to put the genotypes into a separate table that can be indexed.
We recommend to use [slivar](https://github.com/brentp/slivar) instead of gemini unless you have specific use for gemini.

**Comment by dridk** [comment]
Thanks ! 
I m creating my own GUI application based on sqlite like you. So, I am investigating how other project is doing : 
You can have a look here! 
https://github.com/labsquare/cutevariant

Thanks ! I didn't know slivar !

**Comment by brentp** [comment]
cutevariant looks nice!
